server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain,text/html
    min-response-size: 2KB

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30s
  datasource:
    url: jdbc:postgresql://localhost:5432/perfdb
    username: postgres
    password: postgres
    hikari:
      register-mbeans: true
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 2000
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.generate_statistics: false
      hibernate.jdbc.fetch_size: 200
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

